runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /auth-return-url
  static_files: build/index.html
  upload: build/index.html
- url: /admin
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_files: build/index.html
  upload: build/index.html
- url: /
  static_dir: build