/*
 *
 * Home constants
 *
 */

export const DEFAULT_ACTION = 'app/Home/DEFAULT_ACTION';
export const CALL_STEAM_AUTHENTICATE = 'app/Home/CALL_STEAM_AUTHENTICATE';
export const GET_INVENTORY_SUCCESS = 'app/Home/GET_INVENTORY_SUCCESS';
export const GET_PROFILE_SUCCESS = 'app/Home/GET_PROFILE_SUCCESS';
export const GET_INVENTORY_FAIL = 'app/Home/GET_INVENTORY_FAIL';
export const GET_PROFILE_FAIL = 'app/Home/GET_PROFILE_FAIL';
export const GET_BOT_ITEMS = 'app/Home/GET_BOT_ITEMS';
export const GET_BOT_ITEMS_SUCCESS = 'app/Home/GET_BOT_ITEMS_SUCCESS';
export const GET_BOT_ITEMS_FAIL = 'app/Home/GET_BOT_ITEMS_FAIL';
export const LOGOUT_STEAM = 'app/Home/LOGOUT_STEAM';
export const SELECT_PLAYER_ITEM = 'app/Home/SELECT_PLAYER_ITEM';
export const REMOVE_PLAYER_ITEM = 'app/Home/REMOVE_PLAYER_ITEM';
export const SELECT_BOT_ITEM = 'app/Home/SELECT_BOT_ITEM';
export const REMOVE_BOT_ITEM = 'app/Home/REMOVE_BOT_ITEM';
export const UPDATE_TRADE_URL = 'app/Home/UPDATE_TRADE_URL';
export const CREATE_NEW_OFFER = 'app/Home/CREATE_NEW_OFFER';
export const OFFER_ADD_TO_QUEUE_SUCCESS = 'app/Home/OFFER_ADD_TO_QUEUE_SUCCESS';
export const CREATE_NEW_OFFER_FAIL = 'app/Home/CREATE_NEW_OFFER_FAIL';
export const TRADE_URL_VERIFIED = 'app/Home/TRADE_URL_VERIFIED';
export const TRADE_URL_UNVERIFIED = 'app/Home/TRADE_URL_UNVERIFIED';
export const TOGGLE_RESULT_MODAL = 'app/Home/TOGGLE_RESULT_MODAL';
export const TOGGLE_TRADE_URL_INPUT_MODAL =
  'app/Home/TOGGLE_TRADE_URL_INPUT_MODAL';
export const CLEAR_PLAYER_SELECTED_ITEMS =
  'app/Home/CLEAR_PLAYER_SELECTED_ITEMS';
export const CLEAR_BOT_SELECTED_ITEMS = 'app/Home/CLEAR_BOT_SELECTED_ITEMS';
export const TOOGLE_TRADE_LOADING = 'app/Home/TOOGLE_TRADE_LOADING';
export const GET_OFFER_STATUS = 'app/Home/GET_OFFER_STATUS';
export const NOT_GET_OFFER_STATUS = 'app/Home/NOT_GET_OFFER_STATUS';
export const CREATE_OFFER_SUCCESS = 'app/Home/CREATE_OFFER_SUCCESS';
export const UPDATE_OFFER_STATUS = 'app/Home/UPDATE_OFFER_STATUS';
export const SHOW_SNACKBAR = 'app/Home/SHOW_SNACKBAR';
export const HIDE_SNACKBAR = 'app/Home/HIDE_SNACKBAR';
